name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: yarn && yarn docs:build
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: docs/.vuepress/dist
          git-config-name: GitHub Actions
          git-config-email: github.actions@github.com