name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [15.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
      
    - name: Build
      run: yarn && yarn docs:build
      
    - name: Deploy
      uses: jenkey2011/vuepress-deploy@v2.0.0
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        USER_NAME   : GitHub Actions
        USER_EMAIL  : github.actions@github.com
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist/